name: enfiletesbasket
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  mobile_scanner: ^6.0.2
  flutter_native_splash: ^2.4.3
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  flutter_dotenv: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2 # Ajout pour gérer les icônes d'application

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

# Configuration des icônes de l'application
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app-logo.png" # Icône principale
  min_sdk_android: 21 # Version minimale du SDK Android
