name: 🚀 Deploy API to Heroku (Test & Prod)

on:
  push:
    branches:
      - deploy_back  # Déploiement de test
      - develop      # Déploiement officiel en Production

env:
  DOCKER_CONTEXT: backend/api/enfiletesbaskets
  DOCKERFILE: Dockerfile
  DOCKER_IMAGE_NAME: enfiletesbaskets-api
  HEROKU_APP_NAME: enfiletesbaskets-api

jobs:
  build:
    name: 🛠️ Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🐳 Enable Docker BuildKit
        run: |
          echo "Enabling Docker BuildKit"
          export DOCKER_BUILDKIT=1

      - name: 🔍 Verify Docker Context
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing directory contents:"
          ls -R
          if [ ! -d "${{ env.DOCKER_CONTEXT }}" ]; then
            echo "⚠️ Docker context directory ${{ env.DOCKER_CONTEXT }} does not exist"
            exit 1
          fi
          if [ ! -f "${{ env.DOCKER_CONTEXT }}/${{ env.DOCKERFILE }}" ]; then
            echo "⚠️ Dockerfile ${{ env.DOCKER_CONTEXT }}/${{ env.DOCKERFILE }} does not exist"
            exit 1
          fi

      - name: 🐳 Build Docker Image for Branch
        run: |
          echo "🔧 Building Docker Image for branch ${{ github.ref_name }}"
          if [ "${{ github.ref_name }}" == "deploy_back" ]; then
            docker build -t ${{ env.DOCKER_IMAGE_NAME }}:test -f ${{ env.DOCKER_CONTEXT }}/${{ env.DOCKERFILE }} ${{ env.DOCKER_CONTEXT }}
          elif [ "${{ github.ref_name }}" == "develop" ]; then
            docker build -t ${{ env.DOCKER_IMAGE_NAME }}:latest -f ${{ env.DOCKER_CONTEXT }}/${{ env.DOCKERFILE }} ${{ env.DOCKER_CONTEXT }}
          else
            echo "⚠️ Unsupported branch: ${{ github.ref_name }}"
            exit 1
          fi

      - name: 🐳 Show Docker Images
        run: docker images

      - name: 🛡️ Save Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /var/lib/docker/volumes
