name: 🚀 Deploy to Heroku

on:
  push:
    branches:
      - deploy_back
      - develop

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: enfiletesbaskets-api
  HEROKU_EMAIL: "your-email@example.com"
  APP_DIR: "backend/api/enfiletesbaskets"

jobs:
  deploy:
    name: 🚀 Deploy to Heroku
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🔧 Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: 🔑 Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "🔑 Authenticating with Heroku"
          echo "${HEROKU_API_KEY}" | docker login --username=_ --password-stdin registry.heroku.com
          heroku auth:token

      - name: 🚀 Deploy to Heroku with Heroku Deploy Action
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{ env.HEROKU_EMAIL }}
          appdir: ${{ env.APP_DIR }}
          branch: ${{ github.ref_name }}
          usedocker: true
