name: 🚀 Deploy API to Heroku (Test & Prod)

on:
  push:
    branches:
      - deploy_back  # Déploiement de test sur la même application
      - develop      # Déploiement officiel en Production

env:
  DOCKER_CONTEXT: backend/api/enfiletesbaskets
  DOCKERFILE: Dockerfile
  DOCKER_IMAGE_NAME: enfiletesbaskets-api
  HEROKU_APP_NAME: enfiletesbaskets-api

jobs:
  build:
    name: 🛠️ Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🐳 Build Docker Image
        run: |
          echo "🔧 Building Docker Image"
          docker build -t ${{ env.DOCKER_IMAGE_NAME }} -f ${{ env.DOCKER_CONTEXT }}/${{ env.DOCKERFILE }} ${{ env.DOCKER_CONTEXT }}

      - name: 🐳 Tag Docker Image for Heroku
        run: |
          docker tag ${{ env.DOCKER_IMAGE_NAME }} registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web

      - name: 🐳 Save Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /var/lib/docker/volumes

  deploy-test:
    name: 🚀 Deploy to Heroku (Test on `deploy_back`)
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deploy_back'

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🔑 Authenticate with Heroku
        run: |
          echo "::add-mask::${{ secrets.HEROKU_API_KEY }}"
          echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: 🚀 Push Docker Image to Heroku (Test)
        run: |
          docker push registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web

      - name: 🚀 Release to Heroku (Test)
        run: |
          heroku container:release web --app ${{ env.HEROKU_APP_NAME }}
          heroku config:set ENVIRONMENT=test --app ${{ env.HEROKU_APP_NAME }}

  deploy-prod:
    name: 🚀 Deploy to Heroku (Production on `develop`)
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🔑 Authenticate with Heroku
        run: |
          echo "::add-mask::${{ secrets.HEROKU_API_KEY }}"
          echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: 🚀 Push Docker Image to Heroku (Prod)
        run: |
          docker push registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web

      - name: 🚀 Release to Heroku (Prod)
        run: |
          heroku container:release web --app ${{ env.HEROKU_APP_NAME }}
          heroku config:set ENVIRONMENT=prod --app ${{ env.HEROKU_APP_NAME }}
